# Generated by Django 2.2.5 on 2022-04-02 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20220401_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='created',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='created',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='houserule',
            name='created',
        ),
        migrations.RemoveField(
            model_name='houserule',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='created',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created',
        ),
        migrations.RemoveField(
            model_name='room',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='updated',
        ),
    ]
