# Generated by Django 2.2.5 on 2022-04-15 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_auto_20220408_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfile', models.FileField(upload_to='musics/')),
                ('caption', models.CharField(max_length=80)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='rooms.Room')),
            ],
        ),
    ]
