# Generated by Django 2.2.5 on 2022-04-02 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='updated',
        ),
    ]
